version: 2.1

executors:
  java-executor:
    docker:
      - image: selenium/standalone-chrome:latest
    working_directory: ~/repo

jobs:
  config:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Instalar Herramientas
          command: |
            apt-get update
            apt-get install -y wget unzip openjdk-17-jdk
      - run:
          name: Dar permisos a Gradlew para ejecución
          command: |
            chmod +x ./gradlew
      - run:
          name: Verificar versiones de Chrome y Driver
          command: |
            google-chrome --version
            chromedriver --version

  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Construir y Compilar Proyecto
          command: |
            ./gradlew clean build -x test

  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Ejecutar E2E Test
          command: |
            ./gradlew clean test -Dwebdriver.chrome.driver=/usr/bin/chromedriver aggregate reports --info --stacktrace

workflows:
  version: 2
  build_and_test:
    jobs:
      - config
      - build:
          requires:
            - config
      - test:
          requires:
            - build
