version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo

jobs:
  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
            unzip gradle-6.8.3-bin.zip
            export PATH=$PATH:~/repo/gradle-6.8.3/bin
      - run:
          name: Run tests
          command: gradle clean test aggregate reports --info --stacktrace

workflows:
  version: 2
  test:
    jobs:
      - test
