version: 2.1

executors:
  java-executor:
    docker:
      - image: selenium/standalone-chrome:latest
    working_directory: ~/repo

jobs:
  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip openjdk-17-jdk
      - run:
          name: Give Gradle wrapper execute permissions
          command: chmod +x ./gradlew
      - run:
          name: Check Chrome and ChromeDriver versions
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Run tests
          command: ./gradlew clean test -Dwebdriver.chrome.driver=/usr/bin/chromedriver aggregate reports --info --stacktrace
      - store_artifacts:
          path: build/reports/tests
          destination: test-results

workflows:
  version: 2
  test:
    jobs:
      - test
